# CLUB algorithm draft - Online Clustering of Bandits

In [9]:
import numpy as np
import numpy.random as npr
import numpy.linalg
import pandas as pd

## Initialisation

In [86]:
#itérations
T=10
#nombre d'utilisateurs
n_user=5
#dimension des catégories/labels à prédire
D=3
#matrice M_i associée à l'approximation des paramètres du cluster j(i)
#paramètre b_i associé à l'approximation des paramètres du cluster j(i)
d_M=dict()
d_b=dict()
for i in range(n_user):
    d_M['M%d' % i]=np.identity(D)
    d_b['b%d' % i]=np.zeros(D)
    
#nombre de clusters estimé
m=1
#nombre de clusters réel (supposé constant pour chaque période)
c=10          
#variation autour de la payoff (white noise)
sigma=1
#nombre de users dans chaque cluster

#initialiser omega
omega=np.ones(D)
#init vecteur V du graphe réel
V=np.ones(n_user)
#paramètre du confidence bound
alpha=1

## Création de données synthétiques

In [84]:
#vecteur u_j pour chaque cluster estimé j=1...m


## Algo CLUB

In [90]:
T=1
for t in range(T):
    #choisir aléatoirement un user i
    i=int(npr.uniform(0,n_user))+1
    #reçoit contexte C_it généré aléatoirement [A METTRE A JOUR]
    C=npr.uniform(size=[D,c])
    #genere omega
    omega=np.linalg.inv(M)*b
    #détermine j_t(i)
    j_hat=V[i]
    #calcule M_bar et b_bar et omega aggrégés
    M_index=[k for k in V if k==j_hat]
    M_sum=sum([d_M['M'+str(int(k))] for k in M_index])
    M_bar=np.identity(D)+M_sum-len(M_index)*np.identity(D)
    b_bar=sum([d_b['b'+str(int(k))] for k in M_index])
    omega_bar=np.dot(np.linalg.inv(M_bar),b_bar)
    #détermine k_t optimal pour cluster j_t(i)
    vect_k=np.zeros(c)
    for k in range(c):
        CB=alpha*np.sqrt(np.dot(np.dot(C[:,k].T,np.linalg.inv(M_bar)),C[:,k])*np.log(t+1))
        vect_k[k]=CB+np.dot(omega_bar.T,C[:,k])
        print(vect_k[k])
    k_t=[v for v in range(c) if vect_k[v]==np.max(vect_k)]
    #calcule payoffs
    
    


0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [77]:
A=np.ones([3,3])

A[2,1]=0
print(A)
A=A.T
print(A)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  0.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  0.]
 [ 1.  1.  1.]]


In [42]:
C

array([[ 0.68213805,  0.50775345,  0.18364261,  0.47887327,  0.53222064,
         0.04322606,  0.09946843,  0.46870691,  0.6117551 ,  0.99944931],
       [ 0.68514888,  0.69585288,  0.22110171,  0.80952001,  0.95222109,
         0.26913348,  0.63699043,  0.35393434,  0.11382247,  0.98555829],
       [ 0.1752772 ,  0.07976344,  0.73425109,  0.19963325,  0.68539193,
         0.05150621,  0.36951962,  0.36933799,  0.91472926,  0.03736494]])